---
name: Build Spack env

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-spack-env:
    strategy:
      fail-fast: false
      matrix:
        env:
          - kokkos-before-fix.yaml
          - kokkos-after-fix.yaml
        os: [ubuntu-26.04]
    runs-on: ${{matrix.os}}
    permissions:
      packages: write  # Required to push to registry
    steps:
      - name: Checkout built branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Set up Spack
        uses: spack/setup-spack@16b756799ede8b28951287f89bcd3fdb32ec1ca3  # v3.0.0
        with:
          spack_ref: v1.2.2
          buildcache: false
      - name: Prepare environment
        shell: spack-bash {0}
        run: |
          spack bootstrap now
          spack env create . ${{matrix.env}}
          spack --env . config add config:install_tree:padded_length:128
          spack --env . repo update
          spack --env . buildcache list
      - name: Install
        shell: spack-bash {0}
        run: |
          spack --env . concretize
          spack --env . install --fail-fast --include-build-deps --show-log-on-error
      - name: Push packages and update index
        shell: spack-bash {0}
        env:
          GITHUB_USER: ${{github.actor}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: spack --env . buildcache push --fail-fast --update-index local-buildcache
        if: ${{!cancelled()}}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          repository: gyselax/spack
          path: gyselax-spack
          ref: releases/v2026.06
      - name: Install GMGPolar
        shell: spack-bash {0}
        run: |
          spack --env . repo add gyselax-spack/spack_repo/patches_common
          spack --env . add gmgpolar target=$(spack arch --target)
          spack --env . install
